### ISSUE TITLE
Návrh API nesecifikuje jak reagovat v případě nekonzistence requestu

### ISSUE THREAD

**Issue by gorn** [gorn/mlcaklikej-be#1]
Dobrý den, začínám pracovat na vašem zadání pro dnešní pohovor a narazil jsem na nejasnost v návrhu API. Nějak to vyřeším, ale v zadádní se píše, že je možno kontaktovat @vratislav nebo @zuzecp, tak to zkouším. Jde "Applifting FullStack test - STFUANDCLICK.com" a následující nejasnost:

V popisovaném API je endpoint /api/v1/klik kter7 v těle requestu obsahuje team a session. V případě, že je session nové, je jasné že je jí třeba vytvořit a zapamatovat si pro jaký je team. V případě že se jedná o již existující session je tedy hodnota "team" již zbytečná, z GUI a celkového flow aplikace vyplývá, že s tímto session stringem už jse na stránce teamu a tam už se kliká jen pro tento team. To by nevadilo, nejasné ale je jak reagovat, pokud v requestu sice "team" bude uveden, ale bude tam jiný než ten původní. 

Navrhované řešení - vráti v response chybu. Jistě by šlo situaci ošetřit i tak aby  pod jedním session šlo klikat pro více teamů (a přizpůsobit tomu strukturu Backend databáze), ale podle mě je to v rozporu se zamýšleným smyslem aplikace - v dokumenntaci se navíc jasně píše že session string se generuje až poté co zvolím team (čili uživatel sám bez hackování toho krajního stavu nedosáhne).

**Comment by gorn** [comment]
Na základě telefonátu ponechám navrhované řešení. V bussiness případě bych to řešil změnou specifikace API.

**Comment by Vratislav** [comment]
Ahoj @gorn, ano máš pravdu. API dovoluje nekonzistentní input. Uprav jak je třeba :) 

Good catch!
VKJ

**Comment by gorn** [comment]
V pohodě, omlouvám se možná za přílišnou starostlivost, já prostě radši chyby chytám už v návrhu, dřív než mi skočí po krku.

**Comment by Vratislav** [comment]
Za mě super proaktivní přístup. 👏
